const { test, expect } = require('@playwright/test');
const fs=require('fs');const path=require('path');
const shotsDir=path.join(process.cwd(),'test-results','qa-screenshots');
function ensureDir(){fs.mkdirSync(shotsDir,{recursive:true});}
function safeName(n){return n.replace(/[^a-z0-9а-яё_-]+/gi,'-').toLowerCase();}
async function screenshot(page,name){ensureDir();await page.screenshot({path:path.join(shotsDir,`${test.info().project.name}-${safeName(name)}.png`),fullPage:true});}
async function collectProblems(page,problems,label){page.on('console',m=>{if(['error','warning'].includes(m.type()))problems.push({type:'console',label,level:m.type(),text:m.text()});});page.on('pageerror',e=>problems.push({type:'pageerror',label,text:e.message}));page.on('requestfailed',r=>problems.push({type:'requestfailed',label,url:r.url(),failure:r.failure()?.errorText||''}));page.on('response',r=>{const s=r.status(),u=r.url();if(s>=400&&!u.includes('/favicon.ico'))problems.push({type:'http',label,status:s,url:u});});}
async function login(page){await page.goto('/admin/login',{waitUntil:'domcontentloaded'});await screenshot(page,'00-login-page');await page.locator('input[name="login"], input[name="username"], input[type="text"]').first().fill(process.env.ADMIN_LOGIN||'manager');await page.locator('input[name="password"], input[name="pass"], input[type="password"]').first().fill(process.env.ADMIN_PASSWORD||'change-me');await Promise.all([page.waitForURL(/\/admin/,{timeout:20000}).catch(()=>page.waitForLoadState('networkidle')),page.getByRole('button',{name:/войти/i}).click()]);await screenshot(page,'01-admin-dashboard');}
async function openByNav(page,text,shot){const link=page.getByRole('link',{name:new RegExp(text,'i')}).first();if(await link.count()){await link.click();await page.waitForLoadState('networkidle').catch(()=>{});await page.waitForTimeout(400);await screenshot(page,shot);}}
async function saveCurrentForm(page){const save=page.getByRole('button',{name:/сохранить/i}).first();if(await save.count()){await save.click();await page.waitForLoadState('networkidle').catch(()=>{});await page.waitForTimeout(700);}}
test('Full QA: админка, лендинг, страница памяти',async({page})=>{const problems=[];await collectProblems(page,problems,'main');await login(page);for(const [n,s] of [['CRM','30-crm-board'],['Заявки семьи','31-submissions'],['Компания','32-company'],['Уведомления','33-notifications'],['Домен','34-domain-seo'],['Версии','35-versions'],['Аналитика','36-analytics'],['Безопасность','37-security'],['Экспорт','38-export-backup']])await openByNav(page,n,s);await openByNav(page,'B2C','10-landing-editor');const title=page.locator('input[name*="title"], textarea[name*="title"], input[name*="hero"], textarea[name*="hero"]').first();if(await title.count())await title.fill('Тестовый лендинг Память QR');await screenshot(page,'11-landing-before-save');await saveCurrentForm(page);await screenshot(page,'12-landing-after-save');await openByNav(page,'Страницы памяти','20-memorials-list');const edit=page.getByRole('link',{name:/редактировать/i}).first();if(await edit.count()){await edit.click();await page.waitForLoadState('networkidle').catch(()=>{});await page.waitForTimeout(500);await screenshot(page,'21-memorial-editor');}const name=page.locator('input[name="full_name"], input[name*="name"]').first();if(await name.count())await name.fill('Тестовый Алексей Николаевич Орлов');await screenshot(page,'22-memorial-before-save');await saveCurrentForm(page);await screenshot(page,'23-memorial-after-save');ensureDir();fs.writeFileSync(path.join(shotsDir,`problems-${test.info().project.name}.json`),JSON.stringify(problems,null,2),'utf8');const serious=problems.filter(p=>!(p.type==='console'&&/favicon|ResizeObserver/i.test(p.text)));expect(serious,JSON.stringify(serious,null,2)).toEqual([]);});
